<?php

namespace ContainerRVnxUBe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPumlCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\PumlCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\PumlCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('make:puml', [], 'Create puml class diagram from Entities', false, #[\Closure(name: 'App\\Command\\PumlCommand')] fn (): \App\Command\PumlCommand => ($container->privates['App\\Command\\PumlCommand'] ?? $container->load('getPumlCommandService')));
    }
}
