<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRVnxUBe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRVnxUBe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRVnxUBe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRVnxUBe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRVnxUBe\App_KernelDevDebugContainer([
    'container.build_hash' => 'RVnxUBe',
    'container.build_id' => '3c6883c9',
    'container.build_time' => 1743596901,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRVnxUBe');
