<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGuX6Jy0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGuX6Jy0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGuX6Jy0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGuX6Jy0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGuX6Jy0\App_KernelDevDebugContainer([
    'container.build_hash' => 'GuX6Jy0',
    'container.build_id' => '57d20d20',
    'container.build_time' => 1743067590,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGuX6Jy0');
