<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRLv3sex\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRLv3sex/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRLv3sex.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRLv3sex\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRLv3sex\App_KernelDevDebugContainer([
    'container.build_hash' => 'RLv3sex',
    'container.build_id' => '92514fb8',
    'container.build_time' => 1742812358,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRLv3sex');
